[build]
command = "npm run build && npm run pages:build"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = ".vercel/output/static"

[env.production]
routes = [
  { pattern = "/*", script = "static" }
] 